name: Scheduled Telegram Message

on:
  schedule:
    - cron: '0 9 * * 5'
      timezone: 'Europe/Moscow'
    - cron: '0 13 * * 0'
      timezone: 'Europe/Moscow'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Send scheduled message to Telegram
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d '{
            "chat_id": "${{ secrets.GROUP_CHAT_ID }}",
            "text": "Всем привет! Это пятнично-воскресный волшебный пинг, о необходимости заполнения файла по недельным действиям, в рамках отчета для CEO, по Заповедям. Чек-лист в закрепленном сообщении. Ссылка на файл для заполнения https://docs.google.com/spreadsheets/d/1we0CaU__X9lJ5tPDLY-V6vpo30ps58g4CDjvyJHsIG8/edit?usp=sharing. Не благодарите)"
          }'
